NovaBibiotecaVirtual/Models/ErrorViewModel.cs
namespace NovaBibiotecaVirtual.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NovaBibiotecaVirtual/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NovaBibiotecaVirtual.Models;
using System.Diagnostics;

namespace NovaBibiotecaVirtual.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NovaBibiotecaVirtual/Controllers/LivroController.cs
using Microsoft.AspNetCore.Mvc;

namespace NovaBibiotecaVirtual.Controllers
{
    public class LivroController : Controller
    {
        //Actions são as páginas e rotas
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        public IActionResult Editar()
        {
            return View();
        }

        public IActionResult Apagar()
        {
            return View();
        }

        public IActionResult ConfirmaraApagar()
        {
            return View();
        }
    }
}

NovaBibiotecaVirtual/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo(a)!</h1>
    <p>Sistema Escolar Biblioteca Virtual</p>
</div>

NovaBibiotecaVirtual/Views/Livro/Apagar.cshtml
@{
    ViewData["Title"] = "Deletar Cadastro Livro";
}

<div class="text-center">

    <h1 class="display-4">Deletar o Cadastro do Livro (XXXXXXXX) ? </h1>

</div>
    

  <a class="btn btn-danger btn-block" role="button" asp-controller="Livro" asp-action="ConfirmarApagar" >Deletar</a>
  <a class="btn btn-primary" role="button" asp-controller="Livro" asp-action="Index">Cancelar</a>

NovaBibiotecaVirtual/Views/Livro/Cadastrar.cshtml
@{
    ViewData["Title"] = "Cadastrar Novo Livro";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Novo Livro</h1>

</div>

<form>

<!--
    <label for="titulo"></label>
    <input type="text" class="form-control"  placeholder="Digite Título do Livro">  </div>
    -->

    <!-- 2 column grid layout with text inputs for the first and last names -->
  <div class="row mb-4">
    <div class="col">
      <div class="form-outline">
        <input type="text" id="titulo" class="form-control" placeholder="Digite o Título do Livro" />
        <label class="form-label" for="titulo">Título do Livro</label>
      </div>
    </div>
    <div class="col">
      <div class="form-outline">
        <input type="text" id="autor" class="form-control" placeholder="Digite o Nome do Autor" />
        <label class="form-label" for="autor">Autor do Livro</label>
      </div>
    </div>
  </div>

  <!-- Text input -->
  <div class="form-outline mb-4">
    <input type="text" id="editora" class="form-control" placeholder="Digite o Nome da Editora" />
    <label class="form-label" for="editora">Editora</label>
  </div>

  <!-- Text input -->
  <div class="form-outline mb-4">
    <input type="number" id="ano" class="form-control" placeholder="Digite o Ano de Publicação" />
    <label class="form-label" for="ano">Ano de Publicação</label>
  </div>

  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="text" id="edicao" class="form-control" placeholder="Digite o Nº da Edição" />
    <label class="form-label" for="edicao">Nº Edição</label>
  </div>

  <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="idioma" class="form-control" placeholder="Digite o Idioma do Livro" />
    <label class="form-label" for="idioma">Idioma do Livro</label>
  </div>

    <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="categoria" class="form-control" placeholder="Digite a Categoria do Livro" />
    <label class="form-label" for="categoria">Categoria do Livro</label>
  </div>

    <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="isbn" class="form-control" placeholder="Digite o Nº ISBN" />
    <label class="form-label" for="isbn">Nº ISBN</label>
  </div>

    <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="cdd" class="form-control" placeholder="Digite o CDD - Decimal de Dewey" />
    <label class="form-label" for="cdd">CDD - Decimal de Dewey</label>
  </div>

     <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="estante" class="form-control" placeholder="Digite a Estante do Livro" />
    <label class="form-label" for="estante">Estante</label>
  </div>

     <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="prateleira" class="form-control" placeholder="Digite a Prateleira do Livro" />
    <label class="form-label" for="prateleira">Prateleira</label>
  </div>

  <!-- Message input -->
  <div class="form-outline mb-4">
    <textarea class="form-control" id="observacoes" rows="4" placeholder="Digite as Observações do Livro"></textarea>
    <label class="form-label" for="observacoes">Observações</label>
  </div>
    

  <button type="submit" class="btn btn-primary">Adicionar</button>
  <a class="btn btn-secondary" asp-controller="Livro" asp-action="Index" role="button">Voltar</a>

</form>

NovaBibiotecaVirtual/Views/Livro/Editar.cshtml
@{
    ViewData["Title"] = "Editar Cadastro Livro";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Novo Livro</h1>

</div>

<form>

<!--
    <label for="titulo"></label>
    <input type="text" class="form-control"  placeholder="Digite Título do Livro">  </div>
    -->

    <!-- 2 column grid layout with text inputs for the first and last names -->
  <div class="row mb-4">
    <div class="col">
      <div class="form-outline">
        <input type="text" id="titulo" class="form-control" placeholder="Digite o Título do Livro" />
        <label class="form-label" for="titulo">Título do Livro</label>
      </div>
    </div>
    <div class="col">
      <div class="form-outline">
        <input type="text" id="autor" class="form-control" placeholder="Digite o Nome do Autor" />
        <label class="form-label" for="autor">Autor do Livro</label>
      </div>
    </div>
  </div>

  <!-- Text input -->
  <div class="form-outline mb-4">
    <input type="text" id="editora" class="form-control" placeholder="Digite o Nome da Editora" />
    <label class="form-label" for="editora">Editora</label>
  </div>

  <!-- Text input -->
  <div class="form-outline mb-4">
    <input type="number" id="ano" class="form-control" placeholder="Digite o Ano de Publicação" />
    <label class="form-label" for="ano">Ano de Publicação</label>
  </div>

  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="text" id="edicao" class="form-control" placeholder="Digite o Nº da Edição" />
    <label class="form-label" for="edicao">Nº Edição</label>
  </div>

  <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="idioma" class="form-control" placeholder="Digite o Idioma do Livro" />
    <label class="form-label" for="idioma">Idioma do Livro</label>
  </div>

    <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="categoria" class="form-control" placeholder="Digite a Categoria do Livro" />
    <label class="form-label" for="categoria">Categoria do Livro</label>
  </div>

    <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="isbn" class="form-control" placeholder="Digite o Nº ISBN" />
    <label class="form-label" for="isbn">Nº ISBN</label>
  </div>

    <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="cdd" class="form-control" placeholder="Digite o CDD - Decimal de Dewey" />
    <label class="form-label" for="cdd">CDD - Decimal de Dewey</label>
  </div>

     <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="estante" class="form-control" placeholder="Digite a Estante do Livro" />
    <label class="form-label" for="estante">Estante</label>
  </div>

     <!-- Number input -->
  <div class="form-outline mb-4">
    <input type="text" id="prateleira" class="form-control" placeholder="Digite a Prateleira do Livro" />
    <label class="form-label" for="prateleira">Prateleira</label>
  </div>

  <!-- Message input -->
  <div class="form-outline mb-4">
    <textarea class="form-control" id="observacoes" rows="4" placeholder="Digite as Observações do Livro"></textarea>
    <label class="form-label" for="observacoes">Observações</label>
  </div>
    

  <button type="submit" class="btn btn-primary">Alterar</button>
  <a class="btn btn-secondary" asp-controller="Livro" asp-action="Index" role="button">Voltar</a>

</form>

NovaBibiotecaVirtual/Views/Livro/Index.cshtml
@{
    ViewData["Title"] = "Listagem de Livros";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start"> <!--Classe para alinhar a direita-->
        <!-- 
            * asp-controller = Serve para identificar controle será usado.
            * asp-action = Serve para identificar qual view será usada.
        -->
        <a class="btn btn-primary" role="button" asp-controller="Livro" asp-action="Cadastrar">Cadastrar Novo Livro</a>
    </div>
    <br />
    <h1 class="display-4">Listagem de Livros</h1>

<table class="table">
    <thead>
        <!--Aqui altera a cor do cabeçalho-->
        <tr>
            <!--Colunas-->
            <th scope="col">#</th>
            <th scope="col">Título do Livro</th>
            <th scope="col">Editora</th>
            <th scope="col">Ano</th>
            <th scope="col">Edição</th>
            <th scope="col">Idioma</th>
            <th scope="col">Categoria</th>
            <th scope="col">ISBN</th>
            <th scope="col">CDD</th>
            <th scope="col">Estante</th>
            <th scope="col">Prateleira</th>
            <th scope="col">Observações</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Delphi 6 - Firebird/Interbase</td>
            <td>Érica</td>
            <td>2006</td>
            <td>1º Edição</td>
            <td>Português</td>
            <td>Informática</td>
            <td>85-7194-845-3</td>
            <td>303.483</td>
            <td>I</td>
            <td>6</td>
            <td>Livro de Programação</td>
            <td>
                <!--Botões-->
                <div class="btn-group" role="group">
                    <a role="button" class="btn btn-warning" asp-controller="Livro" asp-action="Editar">Editar</a>
                    <a role="button" class="btn btn-danger" asp-controller="Livro" asp-action="Apagar">Apagar</a>
                </div>
            </td>

        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Delphi 6 - Firebird/Interbase</td>
            <td>Érica</td>
            <td>2006</td>
            <td>1º Edição</td>
            <td>Português</td>
            <td>Informática</td>
            <td>85-7194-845-3</td>
            <td>303.483</td>
            <td>I</td>
            <td>6</td>
            <td>Livro de Programação</td>
            <td>
                <!--Botões-->
                <div class="btn-group" role="group">
                    <a role="button" class="btn btn-warning" asp-controller="Livro" asp-action="Editar">Editar</a>
                    <a role="button" class="btn btn-danger"  asp-controller="Livro" asp-action="Apagar">Apagar</a>
                </div>
            </td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>Delphi 6 - Firebird/Interbase</td>
            <td>Érica</td>
            <td>2006</td>
            <td>1º Edição</td>
            <td>Português</td>
            <td>Informática</td>
            <td>85-7194-845-3</td>
            <td>303.483</td>
            <td>I</td>
            <td>6</td>
            <td>Livro de Programação</td>
            <td>
                <!--Botões-->
                <div class="btn-group" role="group">
                    <a role="button" class="btn btn-warning" asp-controller="Livro" asp-action="Editar">Editar</a>
                    <a role="button" class="btn btn-danger"  asp-controller="Livro" asp-action="Apagar">Apagar</a>
                </div>
            </td>
        </tr>
    </tbody>
</table>

</div>

NovaBibiotecaVirtual/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bibioteca Virtual</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NovaBibiotecaVirtual.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bibioteca Virtual</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Livro" asp-action="Index">Livros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--Rodapé-->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bibioteca Virtual - Software com Distribuição Gratuita
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>